WebApplication3/Areas/Admin/Controllers/FullContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Areas.Admin.Controllers
{
    public class FullContractController : Controller
    {
		// GET: Admin/FullContract
		QUANLYBDSEntities model = new QUANLYBDSEntities();
		public ActionResult Index()

        {
			var fullcontract = model.Full_Contract.OrderByDescending(x => x.ID).ToList();
            return View(fullcontract);
        }
		[HttpGet]
		public ActionResult Create()
		{
			ViewBag.property = model.Properties.OrderByDescending(x => x.ID).ToList();
			return View();
		}
		[HttpPost]
		public ActionResult Create(Full_Contract c)
		{
			var contract = new Full_Contract();
			contract.FullContractCode = c.FullContractCode;
			contract.CustomerName = c.CustomerName;
			contract.YearOfBirth = c.YearOfBirth;
			contract.SSN = c.SSN;
			contract.CustomerAddress = c.CustomerAddress;
			contract.Mobile = c.Mobile;
			contract.DateOfContract = c.DateOfContract;
			contract.Price = c.Price;
			contract.Deposit = c.Deposit;
			contract.Remain = c.Remain;
			contract.Status = c.Status;
			contract.PropertyID = c.PropertyID;
			model.Full_Contract.Add(contract);
			model.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Edit(int id)
		{
			var fullcontract = model.Full_Contract.FirstOrDefault(x => x.ID == id);
			ViewBag.property = model.Properties.OrderByDescending(x => x.ID).ToList();
			return View(fullcontract);
		}
		[HttpPost]
		public ActionResult Edit(int id, Full_Contract c)
		{
			var contract = model.Full_Contract.FirstOrDefault(x => x.ID == id);
			contract.FullContractCode = c.FullContractCode;
			contract.CustomerName = c.CustomerName;
			contract.YearOfBirth = c.YearOfBirth;
			contract.SSN = c.SSN;
			contract.CustomerAddress = c.CustomerAddress;
			contract.Mobile = c.Mobile;
			contract.DateOfContract = c.DateOfContract;
			contract.Price = c.Price;
			contract.Deposit = c.Deposit;
			contract.Remain = c.Remain;
			contract.Status = c.Status;
			contract.PropertyID = c.PropertyID;
			model.SaveChanges();
			return RedirectToAction("Index");
		}

	}
}

WebApplication3/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
		// GET: Admin/Product
		QUANLYBDSEntities model = new QUANLYBDSEntities();
        public ActionResult Index()
        {
			var property = model.Properties.OrderByDescending(x => x.ID).ToList();
            return View(property);
        }
		[HttpGet]
		public ActionResult Edit(int id)
		{
			var property = model.Properties.FirstOrDefault(x => x.ID == id);
			ViewBag.property_type = model.Property_Type.OrderByDescending(x => x.ID).ToList();
			ViewBag.district = model.Districts.OrderByDescending(x => x.ID).ToList();
			ViewBag.status = model.Property_Status.OrderByDescending(x => x.ID).ToList();
			return View(property);
		}
		[HttpPost]
		public ActionResult Edit(int id, Property p)
		{
			var property = model.Properties.FirstOrDefault(x => x.ID == id);
			property.PropertyName = p.PropertyName;
			property.Price = p.Price;
			property.Description = p.Description;
			property.Avatar = p.Avatar;
			property.Address = p.Address;
			property.Area = p.Area;
			property.BedRoom = p.BedRoom;
			property.BathRoom = p.BathRoom;
			property.DistrictID = p.DistrictID;
			property.PropertyStatusID = p.PropertyStatusID;
			property.PropertyTypeID = p.PropertyTypeID;
			property.InstallmentRate = p.InstallmentRate;
			model.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Create()
		{
			ViewBag.property_type = model.Property_Type.OrderByDescending(x => x.ID).ToList();
			ViewBag.district = model.Districts.OrderByDescending(x => x.ID).ToList();
			ViewBag.status = model.Property_Status.OrderByDescending(x => x.ID).ToList();
			return View();
			
		}
		[HttpPost]
		public ActionResult Create(Property p)
		{
			var property = new Property();
			property.PropertyName = p.PropertyName;
			property.Price = p.Price;
			property.Description = p.Description;
			property.Avatar = p.Avatar;
			property.Address = p.Address;
			property.Area = p.Area;
			property.BedRoom = p.BedRoom;
			property.BathRoom = p.BathRoom;
			property.DistrictID = p.DistrictID;
			property.PropertyStatusID = p.PropertyStatusID;
			property.PropertyTypeID = p.PropertyTypeID;
			property.InstallmentRate = p.InstallmentRate;
			model.Properties.Add(property);
			model.SaveChanges();
			return RedirectToAction("Index");
		} 
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var property = model.Properties.FirstOrDefault(x => x.ID == id);
			return View(property);
		}
		[HttpPost]
		[ActionName ("Delete")]
		public ActionResult DeleteConfirm(int id)
		{
			var property = model.Properties.FirstOrDefault(x => x.ID == id);
			model.Properties.Remove(property);
			model.SaveChanges();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Details(int id)
		{
			var property = model.Properties.FirstOrDefault(x => x.ID == id);
			return View(property);
		}
	}
}

WebApplication3/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Quản lý BĐS</title>
	<!-- Bootstrap core JavaScript-->
	<script src="~/Assets/vendor/jquery/jquery.min.js"></script>
	<script src="~/Assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="~/Assets/vendor/jquery-easing/jquery.easing.min.js"></script>
	<!-- Custom scripts for all pages-->
	<script src="~/Assets/js/sb-admin-2.min.js"></script>

	<!-- Page level plugins -->
	<script src="~/Assets/vendor/datatables/jquery.dataTables.min.js"></script>
	<link href="~/Assets/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<!-- Page level custom scripts -->
	<script src="~/Assets/js/demo/datatables-demo.js"></script>

	<!-- Custom fonts for this template -->
	<link href="~/Assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<!-- Custom styles for this template -->
	<link href="~/Assets/css/sb-admin-2.min.css" rel="stylesheet" />
	<!-- Custom styles for this page -->
	<link href="~/Assets/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Lato&display=swap"
		  rel="stylesheet" />
	<style>
		.full-contract{
			
			margin:0px 50px;
		}

	</style>
</head>

<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
			@Html.ActionLink("Quản Lý Bất Động Sản", "Index", null, new { @class = "sidebar-brand-text mx-3 sidebar-brand d-flex align-items-center justify-content-center", style="font-size: 30px; margin:50px" })

			<!-- Heading -->
			<div class="sidebar-heading">
				Danh mục Quản lý BĐS
			</div>


			<!-- Nav Item - Tables -->
			<li class="nav-item active">
				<a class="nav-link" href="@Url.Action("Index", "Product")">
					<i class="fas fa-fw fa-table"></i>
					<span>Danh sách Bất Động Sản</span>
				</a>
			</li>

			<li class="nav-item active">
				<a class="nav-link" href="@Url.Action("Index", "FullContract")">
					<i class="fas fa-fw fa-table"></i>
					<span>Danh sách các hợp đồng Bất Động Sản thanh toán 1 lần</span>
				</a>
			</li>
			<!-- Divider -->
			<hr class="sidebar-divider d-none d-md-block">

		</ul>
		<!-- End of Sidebar -->
		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			@RenderBody()
			<!-- End of Main Content -->
			<!-- Footer -->
			<footer class="sticky-footer bg-white">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Copyright &copy; Your Website 2019</span>
					</div>
				</div>
			</footer>
			<!-- End of Footer -->

		</div>
		<!-- End of Content Wrapper -->

	</div>
	<!-- End of Page Wrapper -->
	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>

	<!-- Logout Modal-->
	<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
					<button class="close" type="button" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
				<div class="modal-footer">
					<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
					<a class="btn btn-primary" href="login.html">Logout</a>
				</div>
			</div>
		</div>
	</div>

</body>

</html>